# Tool invocations
install_files := libscimpanelcontroller.so ../src/scim_panelcontrol_client.h

install: $(install_files)
	@echo 'Building target: $@'
	@echo 'Copying libscimpanelcontroller.so'
	cp libscimpanelcontroller.so /usr/lib
	@echo 'Copying libscimpanelcontroller.h'
	cp ../src/scim_panelcontrol_client.h /usr/include/scim-1.0
	@echo 'Finished building target: $@'
	@echo ' '

uninstall:
	@echo 'Building target: $@'
	@echo 'Removing libscimpanelcontroller.so'
	rm -f /usr/lib/libscimpanelcontroller.so
	@echo 'Removing libscimpanelcontroller.so'
	rm -f /usr/include/scim-1.0/scim_panelcontrol_client.h
	@echo 'Finished building target: $@'
	@echo ' '
